version: "3.9"
services:
  test:
    image: "lab-2"
    volumes:
      - .:/app
    command: python3 -m pytest
  run:
    image: "lab-2"
    volumes:
      - .:/app
    command: python3 main.py
  run_async:
    image: "lab-2"
    volumes:
      - .:/app
    command: python3 async.py